eco1_config:
  - name: Northern Wetland
    eco: [5]
    nlcd: [90, 95]
  - name: NW Mountain Forest
    eco: [6]
    nlcd: [41, 42, 43]
  - name: NW Mountain Schrub
    eco: [6]
    nlcd: [52]
  - name: NW Mountain Grassland
    eco: [6]
    nlcd: [71]
  - name: Eastern Temperate Forest
    eco: [8]
    nlcd: [41, 42, 43]
  - name: Eastern Temperate Wetlands
    eco: [8]
    nlcd: [90, 95]
  - name: Great Plains Forest
    eco: [9]
    nlcd: [41, 42, 43]
  - name: Great Plains Schrub
    eco: [9]
    nlcd: [52]
  - name: Great Plains Grassland
    eco: [9]
    nlcd: [71]
  - name: Great Plains Wetland
    eco: [9]
    nlcd: [90, 95]
  - name: NA Desert Forest
    eco: [10]
    nlcd: [41, 42, 43]
  - name: NA Desert Schrub
    eco: [10]
    nlcd: [52]
  - name: NA Desert Grassland
    eco: [10]
    nlcd: [71]
  - name: Medit California Forest
    eco: [11]
    nlcd: [41, 42, 43]
  - name: Medit California Schrub
    eco: [11]
    nlcd: [52]
  - name: Medit California Grassland
    eco: [11]
    nlcd: [71]
  - name: Southern Semiarid Schrub
    eco: [12]
    nlcd: [52]
  - name: Temperate Sierra Forest
    eco: [13]
    nlcd: [41, 42, 43]
  - name: Temperate Sierra Schrub
    eco: [13]
    nlcd: [52]
  - name: Temperate Sierra Grassland
    eco: [13]
    nlcd: [71]
  - name: Tropical Wetland
    eco: [15]
    nlcd: [90, 95]

eco3_config_old:
- name: 'North Cascades : Schrub'
  eco_lvl_3:
  - 6205
  nlcd:
  - 52
- name: 'Southern Coastal Plain : Forest'
  eco_lvl_3:
  - 8503
  nlcd:
  - 41
  - 42
  - 43
- name: 'Southern Coastal Plain : Grassland'
  eco_lvl_3:
  - 8503
  nlcd:
  - 71
- name: 'Arizona+New Mexico Mountains : Forest'
  eco_lvl_3:
  - 13101
  nlcd:
  - 41
  - 42
  - 43
- name: 'Columbia Plateau : Schrub'
  eco_lvl_3:
  - 10102
  nlcd:
  - 52
- name: 'Columbia Mountains+Northern Rockies : Grassland'
  eco_lvl_3:
  - 6203
  nlcd:
  - 71
- name: 'California Coastal Sage, Chaparral, and Oak Woodlands : Forest'
  eco_lvl_3:
  - 11101
  nlcd:
  - 41
  - 42
  - 43
- name: 'California Coastal Sage, Chaparral, and Oak Woodlands : Grassland'
  eco_lvl_3:
  - 11101
  nlcd:
  - 71
- name: 'Sierra Nevada : Schrub'
  eco_lvl_3:
  - 6212
  nlcd:
  - 52
- name: 'Sierra Nevada : Forest'
  eco_lvl_3:
  - 6212
  nlcd:
  - 41
  - 42
  - 43
- name: 'Southern Coastal Plain : Wetland'
  eco_lvl_3:
  - 8503
  nlcd:
  - 90
  - 95
- name: 'Western Gulf Coastal Plain : Wetland'
  eco_lvl_3:
  - 9501
  nlcd:
  - 90
  - 95
- name: 'Madrean Archipelago : Forest'
  eco_lvl_3:
  - 12101
  nlcd:
  - 41
  - 42
  - 43
- name: 'Idaho Batholith : Schrub'
  eco_lvl_3:
  - 6215
  nlcd:
  - 52
- name: 'Idaho Batholith : Forest'
  eco_lvl_3:
  - 6215
  nlcd:
  - 41
  - 42
  - 43
- name: 'Southern and Baja California Pine-Oak Mountains : Forest'
  eco_lvl_3:
  - 11103
  nlcd:
  - 41
  - 42
  - 43
- name: 'California Coastal Sage, Chaparral, and Oak Woodlands : Schrub'
  eco_lvl_3:
  - 11101
  nlcd:
  - 52
- name: 'Chihuahuan Desert : Forest'
  eco_lvl_3:
  - 10204
  nlcd:
  - 41
  - 42
  - 43
- name: 'Klamath Mountains : Forest'
  eco_lvl_3:
  - 6211
  nlcd:
  - 41
  - 42
  - 43
- name: 'Southern and Baja California Pine-Oak Mountains : Schrub'
  eco_lvl_3:
  - 11103
  nlcd:
  - 52
- name: 'Columbia Plateau : Grassland'
  eco_lvl_3:
  - 10102
  nlcd:
  - 71
- name: 'Southern Rockies : Grassland'
  eco_lvl_3:
  - 6214
  nlcd:
  - 71
- name: 'Blue Mountains : Grassland'
  eco_lvl_3:
  - 6209
  nlcd:
  - 71
- name: 'Klamath Mountains : Schrub'
  eco_lvl_3:
  - 6211
  nlcd:
  - 52
- name: 'Cascades : Grassland'
  eco_lvl_3:
  - 6207
  nlcd:
  - 71
- name: 'Eastern Cascades Slopes and Foothills : Grassland'
  eco_lvl_3:
  - 6208
  nlcd:
  - 71
- name: 'Southern Coastal Plain : Schrub'
  eco_lvl_3:
  - 8503
  nlcd:
  - 52
- name: 'Southern Florida Coastal Plain : Wetland'
  eco_lvl_3:
  - 15401
  nlcd:
  - 90
  - 95
- name: 'Mojave Basin and Range : Grassland'
  eco_lvl_3:
  - 10201
  nlcd:
  - 71
- name: 'Canadian Rockies : Grassland'
  eco_lvl_3:
  - 6204
  nlcd:
  - 71
- name: 'North Cascades : Grassland'
  eco_lvl_3:
  - 6205
  nlcd:
  - 71
- name: 'Idaho Batholith : Grassland'
  eco_lvl_3:
  - 6215
  nlcd:
  - 71
- name: 'Snake River Plain : Grassland'
  eco_lvl_3:
  - 10108
  nlcd:
  - 71
- name: 'Klamath Mountains : Grassland'
  eco_lvl_3:
  - 6211
  nlcd:
  - 71
- name: 'Central Basin and Range : Grassland'
  eco_lvl_3:
  - 10105
  nlcd:
  - 71
- name: 'Northern Basin and Range : Grassland'
  eco_lvl_3:
  - 10103
  nlcd:
  - 71
- name: 'Southern and Baja California Pine-Oak Mountains : Grassland'
  eco_lvl_3:
  - 11103
  nlcd:
  - 71
- name: 'Sierra Nevada : Grassland'
  eco_lvl_3:
  - 6212
  nlcd:
  - 71
- name: 'Arizona+New Mexico Mountains : Grassland'
  eco_lvl_3:
  - 13101
  nlcd:
  - 71

eco3_config:
- name: 'Middle Rockies : Grassland'
  eco_lvl_3:
  - 6210
  nlcd:
  - 71
- name: 'Southeastern Plains : Grassland'
  eco_lvl_3:
  - 8305
  nlcd:
  - 71
- name: 'Cascades : Schrub'
  eco_lvl_3:
  - 6207
  nlcd:
  - 52
- name: 'Arizona+New Mexico Mountains : Forest'
  eco_lvl_3:
  - 13101
  nlcd:
  - 41
  - 42
  - 43
- name: 'Columbia Plateau : Schrub'
  eco_lvl_3:
  - 10102
  nlcd:
  - 52
- name: 'California Coastal Sage, Chaparral, and Oak Woodlands : Forest'
  eco_lvl_3:
  - 11101
  nlcd:
  - 41
  - 42
  - 43
- name: 'Sierra Nevada : Forest'
  eco_lvl_3:
  - 6212
  nlcd:
  - 41
  - 42
  - 43
- name: 'Sierra Nevada : Schrub'
  eco_lvl_3:
  - 6212
  nlcd:
  - 52
- name: 'California Coastal Sage, Chaparral, and Oak Woodlands : Grassland'
  eco_lvl_3:
  - 11101
  nlcd:
  - 71
- name: 'Columbia Mountains+Northern Rockies : Grassland'
  eco_lvl_3:
  - 6203
  nlcd:
  - 71
- name: 'Southern Coastal Plain : Wetland'
  eco_lvl_3:
  - 8503
  nlcd:
  - 90
  - 95
- name: 'Western Gulf Coastal Plain : Wetland'
  eco_lvl_3:
  - 9501
  nlcd:
  - 90
  - 95
- name: 'Madrean Archipelago : Forest'
  eco_lvl_3:
  - 12101
  nlcd:
  - 41
  - 42
  - 43
- name: 'Idaho Batholith : Forest'
  eco_lvl_3:
  - 6215
  nlcd:
  - 41
  - 42
  - 43
- name: 'Idaho Batholith : Schrub'
  eco_lvl_3:
  - 6215
  nlcd:
  - 52
- name: 'California Coastal Sage, Chaparral, and Oak Woodlands : Schrub'
  eco_lvl_3:
  - 11101
  nlcd:
  - 52
- name: 'Southern and Baja California Pine-Oak Mountains : Forest'
  eco_lvl_3:
  - 11103
  nlcd:
  - 41
  - 42
  - 43
- name: 'Chihuahuan Desert : Forest'
  eco_lvl_3:
  - 10204
  nlcd:
  - 41
  - 42
  - 43
- name: 'Klamath Mountains : Forest'
  eco_lvl_3:
  - 6211
  nlcd:
  - 41
  - 42
  - 43
- name: 'Southern and Baja California Pine-Oak Mountains : Schrub'
  eco_lvl_3:
  - 11103
  nlcd:
  - 52
- name: 'Columbia Plateau : Grassland'
  eco_lvl_3:
  - 10102
  nlcd:
  - 71
- name: 'Canadian Rockies : Grassland'
  eco_lvl_3:
  - 6204
  nlcd:
  - 71
- name: 'Southern Rockies : Grassland'
  eco_lvl_3:
  - 6214
  nlcd:
  - 71
- name: 'Blue Mountains : Grassland'
  eco_lvl_3:
  - 6209
  nlcd:
  - 71
- name: 'Klamath Mountains : Schrub'
  eco_lvl_3:
  - 6211
  nlcd:
  - 52
- name: 'Eastern Cascades Slopes and Foothills : Grassland'
  eco_lvl_3:
  - 6208
  nlcd:
  - 71
- name: 'Mojave Basin and Range : Grassland'
  eco_lvl_3:
  - 10201
  nlcd:
  - 71
- name: 'Southern Florida Coastal Plain : Wetland'
  eco_lvl_3:
  - 15401
  nlcd:
  - 90
  - 95
- name: 'North Cascades : Grassland'
  eco_lvl_3:
  - 6205
  nlcd:
  - 71
- name: 'Snake River Plain : Grassland'
  eco_lvl_3:
  - 10108
  nlcd:
  - 71
- name: 'Southern Coastal Plain : Schrub'
  eco_lvl_3:
  - 8503
  nlcd:
  - 52
- name: 'Central Basin and Range : Grassland'
  eco_lvl_3:
  - 10105
  nlcd:
  - 71
- name: 'Northern Basin and Range : Grassland'
  eco_lvl_3:
  - 10103
  nlcd:
  - 71
- name: 'Idaho Batholith : Grassland'
  eco_lvl_3:
  - 6215
  nlcd:
  - 71
- name: 'Southern and Baja California Pine-Oak Mountains : Grassland'
  eco_lvl_3:
  - 11103
  nlcd:
  - 71
- name: 'Klamath Mountains : Grassland'
  eco_lvl_3:
  - 6211
  nlcd:
  - 71
